Experimenting with GitHub Actions 22

diff --git a/.github/workflows/run_script.yml b/.github/workflows/run_script.yml
--- a/.github/workflows/run_script.yml
+++ b/.github/workflows/run_script.yml
@@ -54,19 +54,19 @@ jobs:
           echo "Checking ls:"
           ls -lh . || echo "Not found"
 
-      - name: Run training script
+      - name: Run training script 1
         run: |
             PYTHONPATH=. python src/scripts/check.py
 
-      - name: Run training script
+      - name: Run sending script 1
         run: |
             PYTHONPATH=. python src/scripts/send_txt_to_tg.py
 
-      - name: Run training script
+      - name: Run showing script 1
         run: |
             PYTHONPATH=. python src/scripts/read_and_show_metrics_github.py
 
-      - name: Notify success via Telegram
+      - name: Notify success via Telegram 1
         if: success()
         run: |
             curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
@@ -82,7 +82,42 @@ jobs:
             echo "Checking datasets/small:"
             ls -lh datasets/small || echo "Not found"
 
-      - name: Notify failure via Telegram
+      - name: Notify failure via Telegram 1
+        if: failure()
+        run: |
+            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+            -d text="Error GitHub Actions!"
+
+      - name: Run training script 2
+        run: |
+            PYTHONPATH=. python src/scripts/check_2.py
+
+      - name: Run sending script 2
+        run: |
+            PYTHONPATH=. python src/scripts/send_txt_to_tg.py
+
+      - name: Run showing script 2
+        run: |
+            PYTHONPATH=. python src/scripts/read_and_show_metrics_github.py
+
+      - name: Notify success via Telegram 2
+        if: success()
+        run: |
+            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+            -d text="Success GitHub Actions!"
+          
+            for file in src/scripts/*.png; do
+              curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
+                -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+                -F photo=@"$file"
+            done
+          
+            echo "Checking datasets/small:"
+            ls -lh datasets/small || echo "Not found"
+
+      - name: Notify failure via Telegram 2
         if: failure()
         run: |
             curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
