Experimenting with GitHub Actions 18

diff --git a/.github/workflows/run_script.yml b/.github/workflows/run_script.yml
--- a/.github/workflows/run_script.yml
+++ b/.github/workflows/run_script.yml
@@ -10,6 +10,10 @@ jobs:
   run-script:
     runs-on: ubuntu-latest
 
+    env:
+      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -70,6 +74,9 @@ jobs:
                 -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                 -F photo=@"$file"
             done
+          
+            echo "Checking datasets/small:"
+            ls -lh datasets/small || echo "Not found"
           
             for file in results/anomalydae/*; do
               [ -e "$file" ] || continue
